# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RangeChow
email: yuanzhou@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  自律，坚持
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.rangechow.com" # the base hostname & protocol for your site
github_username:  rangechow

# Build settings
markdown: kramdown
encoding: "utf-8"

gems: [jekyll-paginate]
paginate: 3



